server:
  port: 8083
    
eureka:
  client:
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: quiz-service
        uri: lb://quiz-service
        predicates:
        - Path=/quiz/**, /test-quiz/**

      - id: question-service
        uri: lb://question-service
        predicates:
        - Path=/ques/**
